<a href="https://colab.research.google.com/github/btna19/btna19/blob/main/2_Budget_Sales_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
plt.style.use("seaborn-v0_8-whitegrid")
import warnings
warnings.filterwarnings('ignore')

In [ ]:
calender=pd.read_csv("/content/calender.csv")
customers=pd.read_csv("/content/customers.csv", encoding='latin-1')
product=pd.read_csv("/content/product.csv")
territory=pd.read_csv("/content/territory.csv")
sales=pd.read_csv("/content/sales.csv")

CALENDAR DATASET

In [ ]:
calender.head()

,Date,DateKey,Year,Quarter,MonthNum,Month,FiscalYear,FiscalQuarter,FiscalMonthNum,FiscalMonth,MonthYear,MonthYearLong,MonthYearNum,WeekdayNum,Weekday,WeekdayWeekend
0,03-04-2016 00:00,20160403,2016,Q2,4,Apr,FY2016,FQ4,10,Apr,Apr-16,Apr-2016,201604,1,Sun,Weekend
1,04-04-2016 00:00,20160404,2016,Q2,4,Apr,FY2016,FQ4,10,Apr,Apr-16,Apr-2016,201604,2,Mon,Weekday
2,05-04-2016 00:00,20160405,2016,Q2,4,Apr,FY2016,FQ4,10,Apr,Apr-16,Apr-2016,201604,3,Tue,Weekday
3,06-04-2016 00:00,20160406,2016,Q2,4,Apr,FY2016,FQ4,10,Apr,Apr-16,Apr-2016,201604,4,Wed,Weekday
4,07-04-2016 00:00,20160407,2016,Q2,4,Apr,FY2016,FQ4,10,Apr,Apr-16,Apr-2016,201604,5,Thu,Weekday

In [ ]:
calender.columns.to_list()

['Date',
 'DateKey',
 'Year',
 'Quarter',
 'MonthNum',
 'Month',
 'FiscalYear',
 'FiscalQuarter',
 'FiscalMonthNum',
 'FiscalMonth',
 'MonthYear',
 'MonthYearLong',
 'MonthYearNum',
 'WeekdayNum',
 'Weekday',
 'WeekdayWeekend']

In [ ]:
calender.shape

(1461, 16)

CUSTOMER DATASET

In [ ]:
customers.head()

,CustomerKey,FirstName,LastName,FullName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned,AddressLine1,DateFirstPurchase,CommuteDistance
0,11000,Jon,Yang,"Yang, Jon",08-04-1966 00:00,M,M,90000,2,0,Bachelors,Professional,1,0,3761 N. 14th St,22-01-2014 00:00,1-2 Miles
1,11001,Eugene,Huang,"Huang, Eugene",14-05-1965 00:00,S,M,60000,3,3,Bachelors,Professional,0,1,2243 W St.,18-01-2014 00:00,0-1 Miles
2,11002,Ruben,Torres,"Torres, Ruben",12-08-1965 00:00,M,M,60000,3,3,Bachelors,Professional,1,1,5844 Linden Land,10-01-2014 00:00,2-5 Miles
3,11003,Christy,Zhu,"Zhu, Christy",15-02-1968 00:00,S,F,70000,0,0,Bachelors,Professional,0,1,1825 Village Pl.,01-01-2014 00:00,5-10 Miles
4,11004,Elizabeth,Johnson,"Johnson, Elizabeth",08-08-1968 00:00,S,F,80000,5,5,Bachelors,Professional,1,4,7553 Harness Circle,26-01-2014 00:00,1-2 Miles

In [ ]:
customers.columns.to_list()

['CustomerKey',
 'FirstName',
 'LastName',
 'FullName',
 'BirthDate',
 'MaritalStatus',
 'Gender',
 'YearlyIncome',
 'TotalChildren',
 'NumberChildrenAtHome',
 'Education',
 'Occupation',
 'HouseOwnerFlag',
 'NumberCarsOwned',
 'AddressLine1',
 'DateFirstPurchase',
 'CommuteDistance']

In [ ]:
customers = customers[['CustomerKey','Gender','BirthDate','MaritalStatus','YearlyIncome']].copy()

In [ ]:
customers.shape

(18484, 5)

In [ ]:
customers.isnull().sum()

CustomerKey      0
Gender           0
BirthDate        0
MaritalStatus    0
YearlyIncome     0
dtype: int64

PRODUCT DATASET

In [ ]:
product.head()

,ProductKey,ProductName,SubCategory,Category,StandardCost,Color,ListPrice,DaysToManufacture,ProductLine,ModelName,Photo,ProductDescription,StartDate
0,1,Adjustable Race,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,http://www.avising.com/me/LearnPBI/DataSources...,NaN,01-06-1998 00:00
1,2,Bearing Ball,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,http://www.avising.com/me/LearnPBI/DataSources...,NaN,01-06-1998 00:00
2,3,BB Ball Bearing,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,http://www.avising.com/me/LearnPBI/DataSources...,NaN,01-06-1998 00:00
3,4,Headset Ball Bearings,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,http://www.avising.com/me/LearnPBI/DataSources...,NaN,01-06-1998 00:00
4,5,Blade,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,http://www.avising.com/me/LearnPBI/DataSources...,NaN,01-06-1998 00:00

In [ ]:
product.columns.to_list()

['ProductKey',
 'ProductName',
 'SubCategory',
 'Category',
 'StandardCost',
 'Color',
 'ListPrice',
 'DaysToManufacture',
 'ProductLine',
 'ModelName',
 'Photo',
 'ProductDescription',
 'StartDate']

In [ ]:
product = product[['ProductKey','ProductName','SubCategory','Category','ProductLine']].copy()

In [ ]:
product.shape

(606, 5)

In [ ]:
product.isnull().sum()

ProductKey       0
ProductName      0
SubCategory    209
Category       209
ProductLine    226
dtype: int64

In [ ]:
product.loc[product['SubCategory'].isnull()].head()

   ProductKey            ProductName SubCategory Category ProductLine
0           1        Adjustable Race         NaN      NaN         NaN
1           2           Bearing Ball         NaN      NaN         NaN
2           3        BB Ball Bearing         NaN      NaN         NaN
3           4  Headset Ball Bearings         NaN      NaN         NaN
4           5                  Blade         NaN      NaN         NaN

In [ ]:

product = product.dropna()

In [ ]:
product.isnull().sum()

ProductKey     0
ProductName    0
SubCategory    0
Category       0
ProductLine    0
dtype: int64

TERRITORY DATASET

In [ ]:
territory.head()

,SalesTerritoryKey,Region,Country,Group,RegionImage
0,1,Northwest,United States,North America,http://www.avising.com/me/LearnPBI/DataSources...
1,2,Northeast,United States,North America,http://www.avising.com/me/LearnPBI/DataSources...
2,3,Central,United States,North America,http://www.avising.com/me/LearnPBI/DataSources...
3,4,Southwest,United States,North America,http://www.avising.com/me/LearnPBI/DataSources...
4,5,Southeast,United States,North America,http://www.avising.com/me/LearnPBI/DataSources...

In [ ]:
territory.shape

(11, 5)

In [ ]:
territory.columns.to_list()

['SalesTerritoryKey', 'Region', 'Country', 'Group', 'RegionImage']

In [ ]:
territory = territory[['SalesTerritoryKey', 'Region', 'Country', 'Group']].copy()

In [ ]:
territory.isnull().sum()

SalesTerritoryKey    0
Region               1
Country              1
Group                1
dtype: int64

In [ ]:
territory

    SalesTerritoryKey          Region         Country          Group
0                   1       Northwest   United States  North America
1                   2       Northeast   United States  North America
2                   3         Central   United States  North America
3                   4       Southwest   United States  North America
4                   5       Southeast   United States  North America
5                   6          Canada          Canada  North America
6                   7          France          France         Europe
7                   8         Germany         Germany         Europe
8                   9       Australia       Australia        Pacific
9                  10  United Kingdom  United Kingdom         Europe
10                 11             NaN             NaN            NaN

SALES DATASET

In [ ]:
sales.shape

(40852, 25)

In [ ]:
sales.columns.tolist()

['ProductKey',
 'OrderDate',
 'ShipDate',
 'CustomerKey',
 'PromotionKey',
 'SalesTerritoryKey',
 'SalesOrderNumber',
 'SalesOrderLineNumber',
 'OrderQuantity',
 'UnitPrice',
 'TotalProductCost',
 'SalesAmount',
 'TaxAmt',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'StandardCost',
 'List Price',
 'Unnamed: 22',
 'diif std cost',
 'diff list price']

In [ ]:
sales = sales[['ProductKey',
 'OrderDate',
 'ShipDate',
 'CustomerKey',
 'SalesTerritoryKey',
 'SalesOrderNumber',
 'SalesOrderLineNumber',
 'OrderQuantity',
 'UnitPrice',
 'TotalProductCost',
 'SalesAmount',
 'TaxAmt']]

In [ ]:
sales = sales.rename(columns={'TaxAmt':"TaxAmount",'Total sales revenue':"TotalSalesRevenue",'Gross Profit':"GrossProfit"})

In [ ]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40852 entries, 0 to 40851
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ProductKey            40852 non-null  int64
 1   OrderDate             40852 non-null  object
 2   ShipDate              40851 non-null  object
 3   CustomerKey           40851 non-null  float64
 4   SalesTerritoryKey     40851 non-null  float64
 5   SalesOrderNumber      40851 non-null  object
 6   SalesOrderLineNumber  40851 non-null  float64
 7   OrderQuantity         40851 non-null  float64
 8   UnitPrice             40851 non-null  float64
 9   TotalProductCost      40851 non-null  float64
 10  SalesAmount           40851 non-null  float64
 11  TaxAmount             40851 non-null  float64
dtypes: float64(8), int64(1), object(3)
memory usage: 3.7+ MB

In [ ]:
sales['OrderDate'] = pd.to_datetime(sales['OrderDate'], errors='coerce')

In [ ]:
sales['ShipDate'] = pd.to_datetime(sales['ShipDate'],format='mixed')

In [ ]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40852 entries, 0 to 40851
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ProductKey            40852 non-null  int64
 1   OrderDate             16546 non-null  datetime64[ns]
 2   ShipDate              40851 non-null  datetime64[ns]
 3   CustomerKey           40851 non-null  float64
 4   SalesTerritoryKey     40851 non-null  float64
 5   SalesOrderNumber      40851 non-null  object
 6   SalesOrderLineNumber  40851 non-null  float64
 7   OrderQuantity         40851 non-null  float64
 8   UnitPrice             40851 non-null  float64
 9   TotalProductCost      40851 non-null  float64
 10  SalesAmount           40851 non-null  float64
 11  TaxAmount             40851 non-null  float64
dtypes: datetime64[ns](2), float64(8), int64(1), object(1)
memory usage: 3.7+ MB

In [ ]:
sales.isnull().sum()

ProductKey                  0
OrderDate               24306
ShipDate                    1
CustomerKey                 1
SalesTerritoryKey           1
SalesOrderNumber            1
SalesOrderLineNumber        1
OrderQuantity               1
UnitPrice                   1
TotalProductCost            1
SalesAmount                 1
TaxAmount                   1
dtype: int64

In [ ]:
sales.dropna()

,ProductKey,OrderDate,ShipDate,CustomerKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,OrderQuantity,UnitPrice,TotalProductCost,SalesAmount,TaxAmount
0,310,2014-01-01,2014-08-01,21768.0,6.0,SO43697,1.0,2.0,1789.1350,2171.2942,3578.2700,286.2616
1,346,2014-01-01,2014-08-01,28389.0,7.0,SO43698,1.0,2.0,1699.9950,1912.1544,3399.9900,271.9992
2,346,2014-01-01,2014-08-01,25863.0,1.0,SO43699,1.0,2.0,1699.9950,1912.1544,3399.9900,271.9992
3,336,2014-01-01,2014-08-01,14501.0,4.0,SO43700,1.0,2.0,349.5491,413.1463,699.0982,55.9279
4,346,2014-01-01,2014-08-01,11003.0,9.0,SO43701,1.0,2.0,1699.9950,1912.1544,3399.9900,271.9992
...,...,...,...,...,...,...,...,...,...,...,...,...
39173,561,2016-12-09,2016-09-19,12341.0,9.0,SO66078,1.0,1.0,2384.0700,1481.9379,2384.0700,190.7256
39174,541,2016-12-09,2016-09-19,12341.0,9.0,SO66078,2.0,1.0,28.9900,10.8423,28.9900,2.3192
39175,530,2016-12-09,2016-09-19,12341.0,9.0,SO66078,3.0,1.0,4.9900,1.8663,4.9900,0.3992
39176,465,2016-12-09,2016-09-19,12341.0,9.0,SO66078,4.0,1.0,24.4900,9.1593,24.4900,1.9592
39177,491,2016-12-09,2016-09-19,12341.0,9.0,SO66078,5.0,1.0,53.9900,41.5723,53.9900,4.3192

DOWNLOADING REVISED DATASETS

In [ ]:
sales.to_csv("Revised_sales.csv")

In [ ]:

customers.to_csv("Revised_customer.csv")

In [ ]:
product.to_csv("Revised_product.csv")

In [ ]:
territory.to_csv("Revised_territory.csv")

In [ ]:
calender.to_csv("Revised_calender.csv")